from __future__ import annotations

import json
import os
from typing import Any, Dict, List

import httpx


class AIAgent:
    """AI-assisted code generation and explanation helper."""

    def __init__(self) -> None:
        self.api_key = os.getenv("OPENAI_API_KEY")

    def generate_code(self, task: str, language: str = "python") -> str:
        task_text = (task or "").strip()
        if not task_text:
            return "Please provide a clear task description."

        if self.api_key:
            try:
                response = httpx.post(
                    "https://api.openai.com/v1/chat/completions",
                    headers={
                        "Authorization": f"Bearer {self.api_key}",
                        "Content-Type": "application/json",
                    },
                    json={
                        "model": "gpt-4o-mini",
                        "messages": [
                            {
                                "role": "system",
                                "content": "You are a senior software engineer and security advisor. Generate clean production-ready code. Keep the answer to code only.",
                            },
                            {
                                "role": "user",
                                "content": f"Generate {language} code for this task: {task_text}",
                            },
                        ],
                        "temperature": 0.2,
                    },
                    timeout=30,
                )
                response.raise_for_status()
                payload = response.json()
                content = payload["choices"][0]["message"]["content"]
                if content:
                    return content.strip()
            except Exception:
                pass

        task_lower = task_text.lower()
        if "api" in task_lower or "fastapi" in task_lower:
            return self._fastapi_template(task_text)
        if "auth" in task_lower or "login" in task_lower:
            return self._auth_template(task_text)
        if "scan" in task_lower or "security" in task_lower or "vuln" in task_lower:
            return self._scanner_template(task_text)
        if "web" in task_lower or "frontend" in task_lower:
            return self._web_template(task_text)
        return self._generic_template(task_text, language)

    def explain(self, snippet: str) -> Dict[str, List[str]]:
        snippet_text = (snippet or "").strip()
        if not snippet_text:
            return {
                "overview": ["No code snippet was provided."],
                "risks": ["No code exists to analyze."],
                "suggestions": ["Paste code or upload a file for detailed analysis."],
                "sample": ["No snippet provided."],
            }

        overview = ["This code appears to define custom application logic."]
        risks = [
            "Validate all user input before using it in logic or database queries.",
            "Check for insecure secret storage or hardcoded credentials.",
            "Review whether any command execution or external process calls are reachable from user input.",
        ]
        suggestions = [
            "Add input validation and sanitization.",
            "Prefer environment variables for secrets and configuration.",
            "Use secure libraries and explicit error handling.",
        ]
        return {
            "overview": overview,
            "risks": risks,
            "suggestions": suggestions,
            "sample": [snippet_text[:200]],
        }

    def plan(self, goal: str) -> Dict[str, Any]:
        text = (goal or "").strip()
        if not text:
            return {"goal": "", "steps": [], "status": "empty"}

        return {
            "goal": text,
            "steps": [
                "Define the requirement and expected outcome.",
                "Design the architecture and core modules.",
                "Implement the main logic and validations.",
                "Run a security and quality review.",
                "Package the solution and document usage.",
            ],
            "status": "ready",
        }

    def _generic_template(self, task_text: str, language: str) -> str:
        return f"""
# Generated by AI Security Suite
# Task: {task_text}
# Language: {language}

class GeneratedSolution:
    def __init__(self):
        self.task = {task_text!r}

    def run(self):
        print(f"Processing task: {{self.task}}")
        return "Task executed successfully."


if __name__ == "__main__":
    result = GeneratedSolution().run()
    print(result)
"""

    def _fastapi_template(self, task_text: str) -> str:
        return f"""
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel

app = FastAPI(title="Generated API")


class Payload(BaseModel):
    data: str


@app.get("/health")
def health():
    return {{"status": "ok"}}


@app.post("/process")
def process(payload: Payload):
    if not payload.data:
        raise HTTPException(status_code=400, detail="Data is required.")
    return {{"message": "{task_text}", "result": payload.data}}
"""

    def _auth_template(self, task_text: str) -> str:
        return f"""
import jwt
from datetime import datetime, timedelta

SECRET_KEY = "change-me-in-production"


def create_token(user_id: str):
    payload = {{
        "sub": user_id,
        "exp": datetime.utcnow() + timedelta(hours=1),
    }}
    return jwt.encode(payload, SECRET_KEY, algorithm="HS256")


def validate_token(token: str):
    try:
        payload = jwt.decode(token, SECRET_KEY, algorithms=["HS256"])
        return payload
    except Exception:
        return None
"""

    def _scanner_template(self, task_text: str) -> str:
        return f"""
import re


def scan_text(text: str):
    findings = []
    patterns = [
        ("secret", r"(api[_-]?key|secret[_-]?key|token)\\s*[:=]\\s*['\"]?[A-Za-z0-9._-]+"),
        ("sql", r"SELECT\\s+.*\\s+FROM.*WHERE.*"),
        ("shell", r"os\\.system\\(|subprocess\\.call\\(|shell=True"),
    ]
    for category, pattern in patterns:
        if re.search(pattern, text, re.IGNORECASE):
            findings.append({{"category": category, "message": f"Potential {category} issue detected."}})
    return findings
"""

    def _web_template(self, task_text: str) -> str:
        return f"""
<!DOCTYPE html>
<html>
  <body>
    <h1>{task_text}</h1>
    <button onclick="alert('Action triggered')">Run</button>
  </body>
</html>
"""
