from __future__ import annotations

from typing import Dict, List


class AIAgent:
    """Simple AI-like helper for code generation and explanation."""

    def generate_code(self, task: str, language: str = "python") -> str:
        task_text = task.strip()
        if not task_text:
            return "Please provide a clear task description."

        template = f"""
# Generated by AI Security Suite
# Task: {task_text}
# Language: {language}

class GeneratedSolution:
    def __init__(self):
        self.task = {task_text!r}

    def run(self):
        print(f"Processing: {{self.task}}")
        return "Task executed successfully."

if __name__ == "__main__":
    result = GeneratedSolution().run()
    print(result)
"""
        return template

    def explain(self, snippet: str) -> Dict[str, List[str]]:
        return {
            "overview": ["This code appears to be user-defined logic."],
            "risks": [
                "Check for unsafe data handling.",
                "Review input validation.",
                "Validate secret management.",
            ],
            "suggestions": [
                "Add validation layers.",
                "Use secure defaults.",
                "Log anomalies securely.",
            ],
            "sample": [snippet[:120] if snippet else "No snippet provided."],
        }
